export var teachers = [
    {
        id: 0,
        nome: "Alba Cristina Magalhaes Alves de Melo",
        areasInteresse: ["Biologia Computacional", "Computação Paralela", "Sistemas Distribuídos"],
        link_lattes: "http://lattes.cnpq.br/5123602572479168",
        email: "alves@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 1,
        nome: "Aleteia Patricia Favacho de Araujo",
        areasInteresse: ["Computação Paralela", "Sistemas Distribuídos"],
        link_lattes: "http://lattes.cnpq.br/1566076687226024",
        email: "aleteia@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 2,
        nome: "André Costa Drummond",
        areasInteresse: ["Redes de Computadores"],
        link_lattes: "http://lattes.cnpq.br/8525132522308309",
        email: "andred@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 3,
        nome: "Bruno Macchiavello",
        areasInteresse: ["Processamento Digital de Sinais e Multimídia"],
        link_lattes: "http://lattes.cnpq.br/5850453918340560",
        email: "macchiavello@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 4,
        nome: "Camilo Chang Dórea",
        areasInteresse: ["Processamento Digital de Sinais e Multimídia"],
        link_lattes: "http://lattes.cnpq.br/7370796774582075",
        email: "camilodorea@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 5,
        nome: "Carla Cavalcante Koike",
        areasInteresse: ["Hardware", "Robótica"],
        link_lattes: "http://lattes.cnpq.br/4356412661621236",
        email: "ckoike@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 6,
        nome: "Carla Denise Castanho",
        areasInteresse: ["Jogos de Computador"],
        link_lattes: "http://lattes.cnpq.br/2003154270448435",
        email: "carlacastanho@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 7,
        nome: "Cláudia Nalon",
        areasInteresse: ["Lógica", "Matemática da Computação", "Semântica e Raciocínio", "Teoria da Computação"],
        link_lattes: "http://lattes.cnpq.br/7793795625581127",
        email: "nalon@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 8,
        nome: "Cláudia Nalon",
        areasInteresse: ["Lógica", "Matemática da Computação", "Semântica e Raciocínio", "Teoria da Computação"],
        link_lattes: "http://lattes.cnpq.br/7793795625581127",
        email: "nalon@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 9,
        nome: "Daniel de Paula Porto",
        areasInteresse: ["Engenharia de Software", "Gerência de Projetos"],
        link_lattes: "http://lattes.cnpq.br/4163096024457599eng",
        email: "daniel.porto@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 10,
        nome: "Dibio Leandro Borges",
        areasInteresse: ["Inteligência Artificial", "Visão Computacional", "Robótica"],
        link_lattes: "http://lattes.cnpq.br/1808368824068028",
        email: "dibio@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 11,
        nome: "Edison Ishikawa",
        areasInteresse: ["Sistemas Distribuídos", "Sistemas de Software", "Semântica e Raciocínio"],
        link_lattes: "http://lattes.cnpq.br/0765775965717248",
        email: "ishikawa@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 12,
        nome: "Edna Dias Canedo",
        areasInteresse: ["Engenharia de Software", "Mineração de Dados", "Engenharia de Requisitos", "Diversidade de Gênero"],
        link_lattes: "http://lattes.cnpq.br/9554285834432091",
        email: "ednacanedo@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 13,
        nome: "Eduardo Adilo Pelinson Alchieri",
        areasInteresse: ["Sistemas Distribuídos", "Tolerância a Falhas"],
        link_lattes: "http://lattes.cnpq.br/4885132018861296",
        email: "ealchieri@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 14,
        nome: "Fernanda Lima",
        areasInteresse: ["Engenharia de Software", "Representação de Conhecimento", "Semântica e Raciocínio", "Computação Colaborativa e Social", "Informática na Educação", "Interação Humano Computador"],
        link_lattes: "http://lattes.cnpq.br/5881553604748585",
        email: "ferlima@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 15,
        nome: "Fernando Albuquerque",
        areasInteresse: ["Engenharia de Software"],
        link_lattes: "http://lattes.cnpq.br/0766291598953512",
        email: "nando@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 16,
        nome: "Flavio Barros Vidal",
        areasInteresse: ["Inteligência Artificial", "Processamento Digital de Sinais e Multimídia", "Sistemas biométricos", "Visão Computacional"],
        link_lattes: "http://lattes.cnpq.br/0453892715674953",
        email: "fbvidal@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 17,
        nome: "Flavio Leonardo Cavalcanti Moura",
        areasInteresse: ["Métodos Formais", "Lógica", "Teoria da Computação"],
        link_lattes: "http://lattes.cnpq.br/4924037693113808",
        email: "flaviomoura@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 18,
        nome: "Genaina Nunes Rodrigues",
        areasInteresse: ["Engenharia de Software", "Métodos Formais", "Sistemas de Software", "Tolerância a Falhas"],
        link_lattes: "http://lattes.cnpq.br/2966913210268454",
        email: "genaina@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
    {
        id: 19,
        nome: "Genaina Nunes Rodrigues",
        areasInteresse: ["Inteligência Artificial", "Computação Colaborativa e Social", "Informática na Educação"],
        link_lattes: "http://lattes.cnpq.br/2899317637335635",
        email: "genaina@unb.br",
        departamento: "Ciência da Computação",
        sigla_depto: "CIC",
    },
]
