export const teachers = [
    {
        id: 0,
        foto: 'https://cic.unb.br/images/uploads/2016/09/photo_melo-150x150.jpg',
        nome: 'Alba Cristina Magalhaes Alves de Melo',
        areasInteresse: [
            'Biologia Computacional',
            'Computação Paralela',
            'Sistemas Distribuídos',
        ],
        link_lattes: 'http://lattes.cnpq.br/5123602572479168',
        email: 'alves@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: [
            'Introdução à Computação',
            'Introdução à Programação de Computadores',
        ],
    },
    {
        id: 1,
        foto: 'http://www.pesquisar.unb.br/img/fotos/1566076687226024.jpg',
        nome: 'Aleteia Patricia Favacho de Araujo',
        areasInteresse: ['Computação Paralela', 'Sistemas Distribuídos'],
        link_lattes: 'http://lattes.cnpq.br/1566076687226024',
        email: 'aleteia@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Introdução à Cloud Computing', 'Sistemas Operacionais'],
    },
    {
        id: 2,
        foto: 'http://www.pesquisar.unb.br/img/fotos/8525132522308309.jpg',
        nome: 'André Costa Drummond',
        areasInteresse: ['Redes de Computadores'],
        link_lattes: 'http://lattes.cnpq.br/8525132522308309',
        email: 'andred@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Redes de Computadores', 'Redes de Computadores II'],
    },
    {
        id: 3,
        foto: 'http://servicosweb.cnpq.br/wspessoa/servletrecuperafoto?tipo=1&id=K4137729J5',
        nome: 'Bruno Macchiavello',
        areasInteresse: ['Processamento Digital de Sinais e Multimídia'],
        link_lattes: 'http://lattes.cnpq.br/5850453918340560',
        email: 'macchiavello@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: [
            'Processamento Digital de Sinais',
            'Processamento Digital de Sinais II',
        ],
    },
    {
        id: 4,
        foto: 'https://www.cic.unb.br/images/uploads/2016/05/camilo_LISA-150x150.jpg',
        nome: 'Camilo Chang Dórea',
        areasInteresse: ['Processamento Digital de Sinais e Multimídia'],
        link_lattes: 'http://lattes.cnpq.br/7370796774582075',
        email: 'camilodorea@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Processamento de Sinais', 'Processamento de Sinais II'],
    },
    {
        id: 5,
        foto: 'http://www.pesquisar.unb.br/img/fotos/4356412661621236.jpg',
        nome: 'Carla Cavalcante Koike',
        areasInteresse: ['Hardware', 'Robótica'],
        link_lattes: 'http://lattes.cnpq.br/4356412661621236',
        email: 'ckoike@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: [
            'Arquitetura de Computadores',
            'Arquitetura de Computadores II',
        ],
    },
    {
        id: 6,
        foto: 'https://www.cic.unb.br/images/uploads/2016/05/foto_Carla_Castanho-150x150.jpg',
        nome: 'Carla Denise Castanho',
        areasInteresse: ['Jogos de Computador'],
        link_lattes: 'http://lattes.cnpq.br/2003154270448435',
        email: 'carlacastanho@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: [
            'Introdução à Computação',
            'Introdução à Programação de Computadores',
        ],
    },
    {
        id: 7,
        foto: 'https://nalon.org/images/2015-02-13-birthday.jpg',
        nome: 'Cláudia Nalon',
        areasInteresse: [
            'Lógica',
            'Matemática da Computação',
            'Semântica e Raciocínio',
            'Teoria da Computação',
        ],
        link_lattes: 'http://lattes.cnpq.br/7793795625581127',
        email: 'nalon@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Lógica para Computação', 'Lógica para Computação II'],
    },
    {
        id: 8,
        foto: 'https://mat.unb.br/images/fotos_pessoas/docentes/ADAIL.png',
        nome: 'Adail de Castro Cavalheiro',
        areasInteresse: [' Geometria Diferencial ', 'Topologia'],
        link_lattes: 'http://lattes.cnpq.br/3866190415872633',
        email: 'a.c.cavalheiro@mat.unb.br',
        departamento: 'Matemática',
        sigla_depto: 'MAT',
        disciplina: ['Lógica para Computação', 'Matemática Discreta'],
    },
    {
        id: 9,
        foto: 'https://www.cic.unb.br/images/uploads/2016/05/aleteia-150x150.jpg',
        nome: 'Daniel de Paula Porto',
        areasInteresse: ['Engenharia de Software', 'Gerência de Projetos'],
        link_lattes: 'http://lattes.cnpq.br/4163096024457599eng',
        email: 'daniel.porto@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Engenharia de Software', 'Projeto de Software'],
    },
    {
        id: 10,
        foto: 'http://www.pesquisar.unb.br/img/fotos/1808368824068028.jpg',
        nome: 'Dibio Leandro Borges',
        areasInteresse: [
            'Inteligência Artificial',
            'Visão Computacional',
            'Robótica',
        ],
        link_lattes: 'http://lattes.cnpq.br/1808368824068028',
        email: 'dibio@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Inteligência Artificial', 'Inteligência Artificial II'],
    },
    {
        id: 11,
        foto: 'http://www.pesquisar.unb.br/img/fotos/0765775965717248.jpg',
        nome: 'Edison Ishikawa',
        areasInteresse: [
            'Sistemas Distribuídos',
            'Sistemas de Software',
            'Semântica e Raciocínio',
        ],
        link_lattes: 'http://lattes.cnpq.br/0765775965717248',
        email: 'ishikawa@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Estrutura de Dados', 'Tópicos Avançados em Computação'],
    },
    {
        id: 12,
        foto: 'https://www.cic.unb.br/images/uploads/2017/12/IMG_9840-150x150.jpg',
        nome: 'Edna Dias Canedo',
        areasInteresse: [
            'Engenharia de Software',
            'Mineração de Dados',
            'Engenharia de Requisitos',
            'Diversidade de Gênero',
        ],
        link_lattes: 'http://lattes.cnpq.br/9554285834432091',
        email: 'ednacanedo@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Banco de Dados', 'Banco de Dados II'],
    },
    {
        id: 13,
        foto: 'https://www.cic.unb.br/images/uploads/2016/03/alchieri-150x150.jpg',
        nome: 'Eduardo Adilo Pelinson Alchieri',
        areasInteresse: ['Sistemas Distribuídos', 'Tolerância a Falhas'],
        link_lattes: 'http://lattes.cnpq.br/4885132018861296',
        email: 'ealchieri@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Sistemas Distribuídos', 'Sistemas Distribuídos II'],
    },
    {
        id: 14,
        foto: 'http://www.pesquisar.unb.br/img/fotos/5881553604748585.jpg',
        nome: 'Fernanda Lima',
        areasInteresse: [
            'Engenharia de Software',
            'Representação de Conhecimento',
            'Semântica e Raciocínio',
            'Computação Colaborativa e Social',
            'Informática na Educação',
            'Interação Humano Computador',
        ],
        link_lattes: 'http://lattes.cnpq.br/5881553604748585',
        email: 'ferlima@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Interação Humano Computador', 'Sistemas de Informação'],
    },
    {
        id: 15,
        foto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvMrL8nBduZhHIOPMJQ-uG9I50PF-ZXrmKhahSa7zlOwj383FEHetj1JqvzCIWPAMMWhY&usqp=CAU',
        nome: 'Fernando Albuquerque',
        areasInteresse: ['Engenharia de Software'],
        link_lattes: 'http://lattes.cnpq.br/0766291598953512',
        email: 'nando@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Técnicas de Programação', 'Engeharia de Software'],
    },
    {
        id: 16,
        foto: 'http://www.pesquisar.unb.br/img/fotos/0453892715674953.jpg',
        nome: 'Flavio Barros Vidal',
        areasInteresse: [
            'Inteligência Artificial',
            'Processamento Digital de Sinais e Multimídia',
            'Sistemas biométricos',
            'Visão Computacional',
        ],
        link_lattes: 'http://lattes.cnpq.br/0453892715674953',
        email: 'fbvidal@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: [
            'Organização e Arquitetura de Computadores',
            'Arquitetura de Computadores',
        ],
    },
    {
        id: 17,
        foto: 'https://www.cic.unb.br/images/uploads/2016/05/flavio2-150x150.jpg',
        nome: 'Flavio Leonardo Cavalcanti Moura',
        areasInteresse: ['Métodos Formais', 'Lógica', 'Teoria da Computação'],
        link_lattes: 'http://lattes.cnpq.br/4924037693113808',
        email: 'flaviomoura@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Lógica Computacional', 'Projeto e Análise de Algoritmos'],
    },
    {
        id: 18,
        foto: 'http://www.pesquisar.unb.br/img/fotos/2966913210268454.jpg',
        nome: 'Genaina Nunes Rodrigues',
        areasInteresse: [
            'Engenharia de Software',
            'Métodos Formais',
            'Sistemas de Software',
            'Tolerância a Falhas',
        ],
        link_lattes: 'http://lattes.cnpq.br/2966913210268454',
        email: 'genaina@unb.br',
        departamento: 'Ciência da Computação',
        sigla_depto: 'CIC',
        disciplina: ['Engenharia de Software', 'Engenharia de Software II'],
    },
    {
        id: 19,
        foto: 'https://mat.unb.br/images/fotos_pessoas/docentes/CARLOS_MABER.png',
        nome: 'Carlos M. C. Riveros',
        areasInteresse: [
            'Geometria Diferencial',
            'Hipersuperfícies de Dupin em espaços Euclidianos',
        ],
        link_lattes: 'http://lattes.cnpq.br/8908621812866982',
        email: 'genaina@unb.br',
        departamento: 'Matemática',
        sigla_depto: 'MAT',
        disciplina: ['Cálculo Numérico', 'Cálculo'],
    },
]
